name: CustomMobs
version: 1.0.0
author: Pandaaa
main: ca.pandaaa.custommobs.CustomMobs
api-version: 1.21
commands:
  custommobs:
    aliases: [cm, mobs, custommobs]
    description: CustomMobs commands.

permissions:
  custommobs.config:
    default: op
  custommobs.admin:
    default: op