name: CustomMobs
version: ${project.version}
author: Pandaaa
main: ca.pandaaa.custommobs.CustomMobs
api-version: 1.21.5
commands:
  custommobs:
    aliases: [cm, mobs, custommobs]
    description: CustomMobs commands.

permissions:
  custommobs.config:
    default: op
  custommobs.admin:
    default: op