name: Package plugin to java archive (JAR)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Clean and package with Maven
        run: mvn clean package
        working-directory: Plugin

      - name: Find CustomMobs jar (non-remapped)
        id: find_jar
        run: |
          JAR_PATH=$(find . -path "*/target/CustomMobs-*.jar" ! -name "*remapped*" | head -n 1)
          echo "Found jar: $JAR_PATH"
          echo "jar_path=$JAR_PATH" >> $GITHUB_OUTPUT

      - name: Upload CustomMobs JAR
        uses: actions/upload-artifact@v4
        with:
          name: CustomMobs
          path: ${{ steps.find_jar.outputs.jar_path }}